version: '3.7'

services:
  app:
    build: ./app
    command: fastapi run ./main.py --port 80
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
      - POSTGRES_HOST=db

  db:
    image: postgres:latest
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
volumes:
  postgres_db_vol:

      